keycloak:
  server-url: http://localhost:8080/
  realm: real-estate
  client-id: real-estate-credential-id
  grant-type: password
  username: zote
  password: zote
  client-secret: mAONFHck6LiZewGnPR6ixTqZKBVEJjw2
  auth-server-url: ${keycloak.server-url}/realms/real-estate/protocol/openid-connect/token