spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: billingssgabs@gmail.com
    password: dkmc bsem ihej rgdk
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.transport.protocol: smtp
