spring:
  application:
    name: common-service

minio:
  object:
    bucket-name: default
    url: http://localhost:9000
    access-key: XfNtLMzPsBmII8tmjJBx
    secret-key: 9zAw2ubkNMsh5DrgXGl4lPj0T3rrCmJ7pRarl2Z1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

logging:
  level:
    org.springdoc: DEBUG