spring:
  profiles:
    include: common, keycloak
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/user-service
    username: postgres
    password: root
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  application:
    name: user-service
  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

