spring:
  profiles:
    include: common
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/user-service
    username: postgres
    password: root
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  application:
    name: user-service
  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

minio:
  object:
    bucket-name: default
    url: http://localhost:9000
    access-key: XfNtLMzPsBmII8tmjJBx
    secret-key: 9zAw2ubkNMsh5DrgXGl4lPj0T3rrCmJ7pRarl2Z1

logging:
  level:
    org.springdoc: DEBUG