spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/agentDB
      auto-index-creation: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 2000000000000
      max-request-size: 215000000000
      file-size-threshold: 10

server:
  port: 8081

minio:
  object:
    bucket-name: default
    url: http://localhost:9000
    access-key: XfNtLMzPsBmII8tmjJBx
    secret-key: 9zAw2ubkNMsh5DrgXGl4lPj0T3rrCmJ7pRarl2Z1